project:
  type: website

website:
  title: "Sothearith Min"
  navbar:
    left:
      - text: Home Page
        href: index.qmd
      - text: Publications & Talks
        href: publications.qmd
      - text: Certificates
        href: certificates.qmd
      - text: Gallery
        href: gallery.qmd
      - text: Contact/Resume
        href: contacts.qmd

format:
  html:
    theme: cerulean
    toc: true
    toc-location: right
    css: styles.css
